/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/charts/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chart */
        get: operations["chart_api_charts__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_ops_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memory
         * @description System + per-process memory snapshot.
         *
         *     Added 2026-05-29 after diagnosing Windows commit-charge exhaustion
         *     causing hard freezes. Reports:
         *       - System: RAM total/used, pagefile total/used, commit %
         *       - Project processes: RSS/VMS for backend / vite / training subprocs
         *       - Heaviest other python.exe / chrome.exe / claude.exe for context
         *
         *     Frontend `ActiveJobsBadge` polls this and shows a red banner when
         *     commit > 85%, so the user can react before another freeze.
         */
        get: operations["memory_api_ops_memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Status */
        get: operations["data_status_api_data_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_data_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/refresh/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Refresh Status */
        get: operations["refresh_status_api_data_refresh__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/refresh/active/peek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Refresh Active
         * @description Return the most recent refresh job (running or finished), so the UI
         *     can recover progress after a page navigation. None if no jobs ever ran
         *     this process. Frontend's `useActiveRefreshJob` calls this on mount.
         */
        get: operations["refresh_active_api_data_refresh_active_peek_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Markets */
        get: operations["markets_api_data_markets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/symbols/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Symbol */
        post: operations["add_symbol_api_data_symbols_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instruments */
        get: operations["instruments_api_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Holdings */
        get: operations["holdings_api_portfolio_holdings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_portfolio_transactions_get"];
        put?: never;
        /** Add Transaction */
        post: operations["add_transaction_api_portfolio_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/transactions/{tx_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction */
        get: operations["get_transaction_api_portfolio_transactions__tx_id__get"];
        put?: never;
        post?: never;
        /** Delete Transaction */
        delete: operations["delete_transaction_api_portfolio_transactions__tx_id__delete"];
        options?: never;
        head?: never;
        /** Update Transaction */
        patch: operations["update_transaction_api_portfolio_transactions__tx_id__patch"];
        trace?: never;
    };
    "/api/models/screen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screen */
        get: operations["screen_api_models_screen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/predictions/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Predictions */
        get: operations["predictions_api_models_predictions__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiments */
        get: operations["experiments_api_models_experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_models_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollback */
        post: operations["rollback_api_models_rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candidates Endpoint
         * @description Return the full candidate pool (cached per recorder + view + models + base params).
         *     Frontend fetches this ONCE, then applies filter + sort client-side. No filter
         *     query params here — Tier 1 filters apply in the browser.
         *     AI analysis (interpretation + risk flags) is LEFT-JOINed from the store at
         *     serving time onto copied item dicts so the lru-cached pool is never mutated.
         */
        get: operations["candidates_endpoint_api_models_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/candidates/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recompute Start
         * @description Start a background recompute of the candidate pool for the given
         *     view + models. Warms the lru_cache; the subsequent GET /candidates is a
         *     cache hit. Reports progress via GET /candidates/recompute/{job_id}.
         */
        post: operations["recompute_start_api_models_candidates_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/candidates/recompute/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recompute Active */
        get: operations["recompute_active_api_models_candidates_recompute_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/candidates/recompute/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recompute Status */
        get: operations["recompute_status_api_models_candidates_recompute__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/recorders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recorders
         * @description Enumerate all qlib recorders across all experiments with lightweight
         *     summary info (pred date range + cached eval status). Cheap; no pred.pkl load.
         */
        get: operations["list_recorders_api_evaluation_recorders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/active/peek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active Peek
         * @description Return list of currently-evaluating recorder_ids. Empty list when
         *     nothing is running. Frontend ActiveJobsBadge polls this so the chip
         *     persists across page navigation.
         */
        get: operations["active_peek_api_evaluation_active_peek_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Evaluation
         * @description Trigger evaluation for a recorder. Cached; pass force_refresh=true to recompute.
         */
        post: operations["run_evaluation_api_evaluation_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/results/{recorder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Result
         * @description Return the cached eval result for a recorder. 404 if never evaluated.
         */
        get: operations["get_result_api_evaluation_results__recorder_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare
         * @description Side-by-side compare of 2 recorders + paired t-test. Triggers eval on
         *     either or both if not yet cached.
         */
        get: operations["compare_api_evaluation_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/active/peek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Peek */
        get: operations["active_peek_api_inference_active_peek_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inference Status */
        get: operations["inference_status_api_inference_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_inference_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/run-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger */
        post: operations["trigger_api_inference_run_now_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/cache/invalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate
         * @description Called by daily_inference subprocess after appending to recorder.
         *     Restricted to localhost so external traffic can't flush the cache.
         */
        post: operations["invalidate_api_internal_cache_invalidate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/active/peek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Peek */
        get: operations["active_peek_api_analysis_active_peek_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_analysis_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_analysis_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/run-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Now */
        post: operations["run_now_api_analysis_run_now_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get For Symbol */
        get: operations["get_for_symbol_api_analysis__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/analysis/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Internal Refresh */
        post: operations["internal_refresh_api_internal_analysis_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduling/retrain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schedule */
        get: operations["get_schedule_api_scheduling_retrain_get"];
        /** Put Schedule */
        put: operations["put_schedule_api_scheduling_retrain_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduling/retrain/run-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Now */
        post: operations["run_now_api_scheduling_retrain_run_now_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduling/retrain/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrain Job Status
         * @description Return per-retrain-job snapshot (pending/running/done/failed).
         */
        get: operations["retrain_job_status_api_scheduling_retrain_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduling/retrain/jobs/active/peek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrain Active Peek
         * @description Return the most recent retrain job (running or finished). Used by
         *     the global ActiveJobsBadge so progress survives page navigation.
         */
        get: operations["retrain_active_peek_api_scheduling_retrain_jobs_active_peek_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Training
         * @description Start a full retrain (P1). Reuses the shared SchedulerManager so the
         *     concurrency lock + trading-hours guard are shared with cron/run-now.
         */
        post: operations["run_training_api_training_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/jobs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Job */
        get: operations["active_job_api_training_jobs_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["job_status_api_training_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Training Runs */
        get: operations["training_runs_api_training_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptanceResult
         * @description Per-criterion pass/fail against spec §11 thresholds.
         */
        AcceptanceResult: {
            /** Passed */
            passed: boolean;
            /** Details */
            details: {
                [key: string]: boolean;
            };
        };
        /** AddSymbolRequest */
        AddSymbolRequest: {
            /**
             * Symbol
             * @description qlib format e.g. "SH601398"
             */
            symbol: string;
        };
        /** AddSymbolResponse */
        AddSymbolResponse: {
            /** Symbol */
            symbol: string;
            /** Fetched Rows */
            fetched_rows: number;
            /** Message */
            message: string;
        };
        /**
         * AiAnalysis
         * @description Served packet attached to a ScreenItem.
         */
        AiAnalysis: {
            /** Interpretation */
            interpretation: string;
            /** Risk Flags */
            risk_flags?: components["schemas"]["RiskFlag"][];
            /**
             * Stance
             * @default neutral
             * @enum {string}
             */
            stance: "favorable" | "neutral" | "caution";
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * As Of Date
             * @default
             */
            as_of_date: string;
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Adjustments */
            adjustments?: string[];
            /**
             * News Count
             * @default 0
             */
            news_count: number;
            /**
             * Notice Count
             * @default 0
             */
            notice_count: number;
        };
        /** AnalysisJob */
        AnalysisJob: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Analyzed */
            analyzed?: number | null;
            /** As Of Date */
            as_of_date?: string | null;
            /** Error */
            error?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** AnalysisStatus */
        AnalysisStatus: {
            /** Last Run At */
            last_run_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * Is Running
             * @default false
             */
            is_running: boolean;
        };
        /**
         * CandidatesResponse
         * @description Same shape as ScreenResponse; semantically a 'no filters applied' candidate pool
         *     intended for client-side filter + sort. Returned by GET /api/models/candidates.
         *
         *     Includes the list of base model+horizon columns available in the underlying
         *     pred.pkl (e.g. lgbm_1d, lgbm_5d, tra_5d…) so the frontend can render a
         *     model picker, and the subset actually used for the current score when a
         *     custom `models` query param was supplied (None means the pool-time default).
         */
        CandidatesResponse: {
            /** Experiment */
            experiment: string;
            /** Recorder Id */
            recorder_id: string;
            /** Latest Date */
            latest_date: string;
            /** Window Days */
            window_days: number;
            /** Universe Size */
            universe_size: number;
            /** Available Models */
            available_models?: string[];
            /** Active Models */
            active_models?: string[] | null;
            /** Items */
            items: components["schemas"]["ScreenItem"][];
            /** Window Dates */
            window_dates?: string[];
            /** As Of Date */
            as_of_date?: string | null;
            /** Data Latest Date */
            data_latest_date?: string | null;
            /**
             * Data Stale Days
             * @default 0
             */
            data_stale_days: number;
        };
        /** CandleBar */
        CandleBar: {
            /**
             * Time
             * @description ISO date YYYY-MM-DD
             */
            time: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
        };
        /** ChartPayload */
        ChartPayload: {
            /** Symbol */
            symbol: string;
            /** Actual */
            actual: components["schemas"]["CandleBar"][];
            /** Predicted */
            predicted: components["schemas"]["PredictionBar"][];
            /**
             * Forecast
             * @description Future-only predicted bars (dates beyond last actual)
             */
            forecast?: components["schemas"]["PredictionBar"][];
            /**
             * Horizon Markers
             * @description Future markers for 1d/5d/20d horizons drawn on the K-line
             */
            horizon_markers?: components["schemas"]["HorizonMarker"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /**
         * CompareResult
         * @description Side-by-side comparison of two recorders + paired t-test on daily IC.
         */
        CompareResult: {
            a: components["schemas"]["EvalResult"];
            b: components["schemas"]["EvalResult"];
            /** Paired T Stat */
            paired_t_stat: number;
            /** Paired P Value */
            paired_p_value: number;
            /** Significant At 05 */
            significant_at_05: boolean;
            /** Ic Delta */
            ic_delta: number;
            /** Ir Delta */
            ir_delta: number;
            /** Verdict */
            verdict: string;
        };
        /** DataStatus */
        DataStatus: {
            /**
             * Calendar End
             * @description ISO date YYYY-MM-DD of the last trading day
             */
            calendar_end: string;
            /**
             * Calendar Size
             * @description Number of trading days in the calendar
             */
            calendar_size: number;
            /**
             * Instruments Count
             * @description Number of symbols in csi300 (~300)
             */
            instruments_count: number;
            /**
             * Last Refresh At
             * @description ISO UTC timestamp; mtime of calendars/day.txt
             */
            last_refresh_at?: string | null;
            /**
             * Freshness
             * @description One of "fresh" | "stale_1d" | "stale_2d_plus"
             */
            freshness: string;
        };
        /**
         * EvalResult
         * @description Full evaluation result for one recorder.
         */
        EvalResult: {
            /** Recorder Id */
            recorder_id: string;
            /** Experiment */
            experiment: string;
            /** Run Name */
            run_name: string;
            /** Computed At */
            computed_at: string;
            /** Window Start */
            window_start: string;
            /** Window End */
            window_end: string;
            /** Sample Size */
            sample_size: number;
            /** Top K */
            top_k: number;
            /** Cost Bps */
            cost_bps: number;
            scorecard: components["schemas"]["ScorecardData"];
            /** Regimes */
            regimes: components["schemas"]["RegimeMetrics"][];
            acceptance: components["schemas"]["AcceptanceResult"];
        };
        /** EvalRunRequest */
        EvalRunRequest: {
            /** Recorder Id */
            recorder_id: string;
            /**
             * Top K
             * @default 30
             */
            top_k: number;
            /**
             * Cost Bps
             * @default 10
             */
            cost_bps: number;
            /**
             * Force Refresh
             * @default false
             */
            force_refresh: boolean;
        };
        /** ExperimentInfo */
        ExperimentInfo: {
            /** Name */
            name: string;
            /** Latest Recorder Id */
            latest_recorder_id: string;
            /** Latest Metrics */
            latest_metrics?: {
                [key: string]: number;
            };
        };
        /** ExperimentsResponse */
        ExperimentsResponse: {
            /** Experiments */
            experiments: components["schemas"]["ExperimentInfo"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Qlib Ready */
            qlib_ready: boolean;
            /** Calendar End */
            calendar_end?: string | null;
        };
        /** Holding */
        Holding: {
            /** Symbol */
            symbol: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Qty */
            qty: number;
            /** Avg Cost */
            avg_cost: number;
            /** Effective Cost */
            effective_cost: number;
            /** Current Price */
            current_price?: number | null;
            /** Market Value */
            market_value?: number | null;
            /** Unrealized Pnl */
            unrealized_pnl?: number | null;
            /** Unrealized Pnl Pct */
            unrealized_pnl_pct?: number | null;
        };
        /** HoldingsResponse */
        HoldingsResponse: {
            /** Holdings */
            holdings: components["schemas"]["Holding"][];
            /** Total Cost */
            total_cost: number;
            /** Total Market Value */
            total_market_value?: number | null;
            /** Total Unrealized Pnl */
            total_unrealized_pnl?: number | null;
            /** As Of */
            as_of?: string | null;
        };
        /**
         * HorizonMarker
         * @description Per-horizon future prediction packet for a single symbol's chart.
         *
         *     target_price = last_actual_close * (1 + pred_return) when pred_return is
         *     not None; otherwise equal to last_actual_close (rendered as flat marker).
         */
        HorizonMarker: {
            /** Horizon */
            horizon: string;
            /** Target Date */
            target_date: string;
            /** Target Price */
            target_price: number;
            /** Pred Return */
            pred_return?: number | null;
            /** Percentile */
            percentile: number;
            /** Model Agreement */
            model_agreement?: number | null;
            /** Raw Scores */
            raw_scores?: {
                [key: string]: number;
            };
        };
        /**
         * HorizonPrediction
         * @description Per-(stock, horizon) prediction packet.
         *
         *     target_date is the trading day this horizon predicts (latest_date +
         *     1/5/20 trading days). pred_return is the calibrated expected return as
         *     a decimal (e.g. 0.032 = +3.2%), or None when no calibration is loaded.
         *     percentile is 0..100 with 100 = best. model_agreement is 0..1 fraction
         *     of the 3 models that agree on direction (NaN-skip).
         */
        HorizonPrediction: {
            /** Target Date */
            target_date: string;
            /** Pred Return */
            pred_return?: number | null;
            /** Percentile */
            percentile: number;
            /** Model Agreement */
            model_agreement?: number | null;
            /** Raw Scores */
            raw_scores?: {
                [key: string]: number;
            };
        };
        /** InferenceJob */
        InferenceJob: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Error */
            error?: string | null;
            /** New Rows */
            new_rows?: number | null;
            /** Reason */
            reason?: string | null;
        };
        /** InferenceStatus */
        InferenceStatus: {
            /** Last Run At */
            last_run_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * Is Running
             * @default false
             */
            is_running: boolean;
        };
        /** InstrumentItem */
        InstrumentItem: {
            /**
             * Symbol
             * @description e.g. "SH600519"
             */
            symbol: string;
            /**
             * Name
             * @description Chinese name, "" if unknown
             */
            name: string;
        };
        /** InstrumentsResponse */
        InstrumentsResponse: {
            /** Market */
            market: string;
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["InstrumentItem"][];
        };
        /** MarketInfo */
        MarketInfo: {
            /**
             * Name
             * @description "csi300" | "csi500" | "etfs" | "custom" | ...
             */
            name: string;
            /**
             * Label
             * @description Human-readable label, e.g. "沪深300"
             */
            label: string;
            /**
             * Count
             * @description Number of symbols in this market
             */
            count: number;
        };
        /** MarketsResponse */
        MarketsResponse: {
            /** Markets */
            markets: components["schemas"]["MarketInfo"][];
            /**
             * Total
             * @description Sum of all markets' counts with dedup
             */
            total: number;
        };
        /**
         * PredictionBar
         * @description Synthetic candle representing model's predicted close for a target date.
         *
         *     open = prior actual close
         *     close = prior actual close * (1 + score_at_T-2)
         *     high/low computed with a small spread for visibility
         *     score field is the raw model score for cross-reference
         */
        PredictionBar: {
            /** Time */
            time: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Score */
            score: number;
        };
        /** PredictionHistory */
        PredictionHistory: {
            /** Symbol */
            symbol: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Experiment */
            experiment: string;
            /** Points */
            points: components["schemas"]["PredictionPoint"][];
        };
        /** PredictionPoint */
        PredictionPoint: {
            /** Date */
            date: string;
            /** Score */
            score: number;
            /** Rank */
            rank: number;
            /** Universe Size */
            universe_size: number;
            /** Base Scores */
            base_scores?: {
                [key: string]: number;
            };
        };
        /** ProgressInfo */
        ProgressInfo: {
            /**
             * Phase
             * @description One of "init" | "fetch" | "dump" | "benchmark" | "done" (or future phases)
             */
            phase: string;
            /**
             * Current
             * @description Current step (0-indexed start, total when finished)
             */
            current: number;
            /**
             * Total
             * @description Total steps for this phase
             */
            total: number;
            /**
             * Message
             * @description Human-readable status line for this step
             * @default
             */
            message: string;
        };
        /** RecomputeJob */
        RecomputeJob: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Error */
            error?: string | null;
            /**
             * View
             * @default ensemble
             */
            view: string;
            /** Models */
            models?: string[];
            progress?: components["schemas"]["RecomputeProgress"] | null;
        };
        /** RecomputeProgress */
        RecomputeProgress: {
            /** Phase */
            phase: string;
            /** Percent */
            percent: number;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** RecomputeRequest */
        RecomputeRequest: {
            /**
             * View
             * @default ensemble
             */
            view: string;
            /** Models */
            models?: string[];
        };
        /** RecomputeTriggerResponse */
        RecomputeTriggerResponse: {
            /** Status */
            status: string;
            /** Job Id */
            job_id?: string | null;
        };
        /**
         * RecorderSummary
         * @description Lightweight summary for the list view. Computed without full eval.
         */
        RecorderSummary: {
            /** Recorder Id */
            recorder_id: string;
            /** Experiment */
            experiment: string;
            /** Run Name */
            run_name: string;
            /** Created At */
            created_at: string;
            /** Pred Start */
            pred_start?: string | null;
            /** Pred End */
            pred_end?: string | null;
            /** Pred Rows */
            pred_rows?: number | null;
            /**
             * Has Eval
             * @default false
             */
            has_eval: boolean;
            /** Ic Mean */
            ic_mean?: number | null;
            /** Ir */
            ir?: number | null;
            /** Acceptance Passed */
            acceptance_passed?: boolean | null;
        };
        /** RecorderVersion */
        RecorderVersion: {
            /** Recorder Id */
            recorder_id: string;
            /** Experiment */
            experiment: string;
            /** Created At */
            created_at: string;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
        };
        /** RefreshJobStatus */
        RefreshJobStatus: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @description "running" | "done" | "failed"
             */
            status: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Log Tail */
            log_tail?: string | null;
            /** @description Latest structured progress emitted by the refresh script, if any. */
            progress?: components["schemas"]["ProgressInfo"] | null;
        };
        /** RefreshResponse */
        RefreshResponse: {
            /** Job Id */
            job_id: string;
            /** Started At */
            started_at: string;
            /** Message */
            message: string;
        };
        /**
         * RegimeMetrics
         * @description One regime segment's scorecard + label (e.g. '2020-COVID').
         */
        RegimeMetrics: {
            /** Label */
            label: string;
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Sample Size */
            sample_size: number;
            scorecard: components["schemas"]["ScorecardData"];
        };
        /** RetrainScheduleRead */
        RetrainScheduleRead: {
            /**
             * Day Of Week
             * @description 0=Mon, 6=Sun
             */
            day_of_week: number;
            /** Hour */
            hour: number;
            /** Minute */
            minute: number;
            /** Enabled */
            enabled: boolean;
            /** Last Run At */
            last_run_at: string | null;
            /** Next Run At */
            next_run_at: string | null;
        };
        /** RetrainScheduleUpdate */
        RetrainScheduleUpdate: {
            /** Day Of Week */
            day_of_week: number;
            /** Hour */
            hour: number;
            /** Minute */
            minute: number;
            /** Enabled */
            enabled: boolean;
        };
        /** RiskFlag */
        RiskFlag: {
            /** Type */
            type: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "high" | "medium" | "low";
            /** Reason */
            reason: string;
            /** Source */
            source: string;
            /** Source Date */
            source_date: string;
            /**
             * Verified
             * @default true
             */
            verified: boolean;
        };
        /** RollbackRequest */
        RollbackRequest: {
            /**
             * Target
             * @description Which recorder to roll back to (previous_1 = the run before the current one).
             * @default previous_1
             */
            target: string;
        };
        /** RollbackResponse */
        RollbackResponse: {
            /** Status */
            status: string;
            /** Archived Recorder Id */
            archived_recorder_id?: string | null;
            /** New Current Recorder Id */
            new_current_recorder_id?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** RunNowResponse */
        RunNowResponse: {
            /** Status */
            status: string;
            /** Reason */
            reason?: string | null;
            /** Job Id */
            job_id?: string | null;
        };
        /**
         * ScorecardData
         * @description The 8-metric scorecard (per spec §8).
         *
         *     All metrics computed against open-to-open returns + TopK=30 long-only
         *     portfolio with `bps` transaction cost adjustment.
         */
        ScorecardData: {
            /** Ic Mean */
            ic_mean: number;
            /** Ric Mean */
            ric_mean: number;
            /** Icir */
            icir: number;
            /** Top Bottom Spread Monthly */
            top_bottom_spread_monthly: number;
            /** Annual Excess Return */
            annual_excess_return: number;
            /** Ir */
            ir: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Daily Turnover */
            daily_turnover: number;
        };
        /** ScreenItem */
        ScreenItem: {
            /** Rank */
            rank: number;
            /** Symbol */
            symbol: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Score Today */
            score_today: number;
            /** Score Avg */
            score_avg: number;
            /** Rank Avg */
            rank_avg: number;
            /** Days In Top */
            days_in_top: number;
            /**
             * Consensus
             * @default 0
             */
            consensus: number;
            /** Base Scores */
            base_scores?: {
                [key: string]: number;
            };
            /** Last Price */
            last_price?: number | null;
            /** Horizons */
            horizons?: {
                [key: string]: components["schemas"]["HorizonPrediction"];
            };
            /** Pct Change 1D */
            pct_change_1d?: number | null;
            /** Pct Change 3D */
            pct_change_3d?: number | null;
            /** Pct Change 5D */
            pct_change_5d?: number | null;
            /** Pct Change 10D */
            pct_change_10d?: number | null;
            /** Pct Change 20D */
            pct_change_20d?: number | null;
            /** Amplitude */
            amplitude?: number | null;
            /** Vol Ratio */
            vol_ratio?: number | null;
            /**
             * Is New High 20D
             * @default false
             */
            is_new_high_20d: boolean;
            /**
             * Is New High 60D
             * @default false
             */
            is_new_high_60d: boolean;
            /**
             * Is New High 120D
             * @default false
             */
            is_new_high_120d: boolean;
            /** Board */
            board?: string | null;
            /**
             * Is St
             * @default false
             */
            is_st: boolean;
            /** Daily Ranks */
            daily_ranks?: (number | null)[];
            /** Daily Scores */
            daily_scores?: (number | null)[];
            ai_analysis?: components["schemas"]["AiAnalysis"] | null;
        };
        /** ScreenResponse */
        ScreenResponse: {
            /** Experiment */
            experiment: string;
            /** Recorder Id */
            recorder_id: string;
            /** Latest Date */
            latest_date: string;
            /** Window Days */
            window_days: number;
            /** Universe Size */
            universe_size: number;
            /** Items */
            items: components["schemas"]["ScreenItem"][];
        };
        /** TrainRequest */
        TrainRequest: {
            /**
             * Scope
             * @description "full" (P1). Single-algo arrives in P3.
             * @default full
             */
            scope: string;
            /**
             * Force
             * @description Override the trading-hours guard.
             * @default false
             */
            force: boolean;
        };
        /** TrainingJobStatus */
        TrainingJobStatus: {
            /** Job Id */
            job_id: string;
            /**
             * Kind
             * @description "cron" | "manual"
             */
            kind: string;
            /**
             * Status
             * @description "pending" | "running" | "done" | "failed" | "skipped"
             */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Error */
            error?: string | null;
            progress?: components["schemas"]["TrainingProgress"] | null;
            /** Log Tail */
            log_tail?: string | null;
        };
        /** TrainingProgress */
        TrainingProgress: {
            /**
             * Phase
             * @description "universe" | "train" | "ensemble" | "done" (or future phases)
             */
            phase: string;
            /**
             * Current
             * @description Current step (1-based); equals total when finished
             */
            current: number;
            /**
             * Total
             * @description Total steps for this run
             */
            total: number;
            /**
             * Message
             * @description Human-readable status line, e.g. 'training lgbm'
             * @default
             */
            message: string;
        };
        /** TrainingRunRow */
        TrainingRunRow: {
            /** Job Id */
            job_id?: string | null;
            /** Kind */
            kind?: string | null;
            /** Scope */
            scope?: string | null;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Recorder Id */
            recorder_id?: string | null;
            /** Run Name */
            run_name?: string | null;
            /** Error */
            error?: string | null;
            /** Ic Mean */
            ic_mean?: number | null;
            /** Ir */
            ir?: number | null;
            /** Acceptance Passed */
            acceptance_passed?: boolean | null;
        };
        /** Transaction */
        Transaction: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "buy" | "sell";
            /** Qty */
            qty: number;
            /** Price */
            price: number;
            /** Fee */
            fee: number;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Broker */
            broker?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TransactionIn */
        TransactionIn: {
            /** Symbol */
            symbol: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "buy" | "sell";
            /** Qty */
            qty: number;
            /** Price */
            price: number;
            /**
             * Fee
             * @default 0
             */
            fee: number;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Broker */
            broker?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** TransactionUpdate */
        TransactionUpdate: {
            /** Qty */
            qty?: number | null;
            /** Price */
            price?: number | null;
            /** Fee */
            fee?: number | null;
            /** Executed At */
            executed_at?: string | null;
            /** Broker */
            broker?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** TriggerResponse */
        TriggerResponse: {
            /** Status */
            status: string;
            /** Job Id */
            job_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionResponse */
        VersionResponse: {
            current: components["schemas"]["RecorderVersion"];
            previous?: components["schemas"]["RecorderVersion"] | null;
            previous_2?: components["schemas"]["RecorderVersion"] | null;
            /** Next Retrain At */
            next_retrain_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chart_api_charts__symbol__get: {
        parameters: {
            query: {
                /** @description ISO date YYYY-MM-DD */
                start: string;
                /** @description ISO date YYYY-MM-DD */
                end: string;
                with_pred?: boolean;
                experiment?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_ops_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    memory_api_ops_memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    data_status_api_data_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStatus"];
                };
            };
        };
    };
    refresh_api_data_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    refresh_status_api_data_refresh__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_active_api_data_refresh_active_peek_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    } | null;
                };
            };
        };
    };
    markets_api_data_markets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketsResponse"];
                };
            };
        };
    };
    add_symbol_api_data_symbols_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSymbolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddSymbolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    instruments_api_instruments_get: {
        parameters: {
            query?: {
                /** @description Market identifier; use 'all' for union */
                market?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    holdings_api_portfolio_holdings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingsResponse"];
                };
            };
        };
    };
    list_transactions_api_portfolio_transactions_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_transaction_api_portfolio_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_api_portfolio_transactions__tx_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_api_portfolio_transactions__tx_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_api_portfolio_transactions__tx_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screen_api_models_screen_get: {
        parameters: {
            query?: {
                top?: number;
                days?: number;
                min_top?: number;
                experiment?: string | null;
                view?: string;
                /** @description Inclusive lower bound on most-recent close (CNY/share) */
                min_price?: number | null;
                /** @description Inclusive upper bound on most-recent close (CNY/share) */
                max_price?: number | null;
                /** @description Lookback in trading days for pct_change filter */
                pct_change_n?: number;
                /** @description Min pct change over pct_change_n (e.g. 0.05 = +5%) */
                min_pct_change?: number | null;
                max_pct_change?: number | null;
                min_amplitude?: number | null;
                max_amplitude?: number | null;
                min_vol_ratio?: number | null;
                max_vol_ratio?: number | null;
                /** @description 0=off, 20/60/120 = require close to be N-day high */
                new_high_n?: number;
                /** @description Comma list: main,gem,star,bj,etf */
                boards?: string | null;
                exclude_st?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predictions_api_models_predictions__symbol__get: {
        parameters: {
            query?: {
                days?: number;
                experiment?: string | null;
                view?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiments_api_models_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentsResponse"];
                };
            };
        };
    };
    version_api_models_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    rollback_api_models_rollback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidates_endpoint_api_models_candidates_get: {
        parameters: {
            query?: {
                top?: number;
                days?: number;
                min_top?: number;
                experiment?: string | null;
                view?: string;
                /** @description Comma-separated list of base column names (e.g. 'lgbm_1d,lgbm_5d,tra_5d') to use as the ensemble score. When set, takes precedence over `view`. Empty or 'all' → use the pool-time default score (e.g. v9 = 1d+5d cols). */
                models?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_start_api_models_candidates_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecomputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeTriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_active_api_models_candidates_recompute_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeJob"] | null;
                };
            };
        };
    };
    recompute_status_api_models_candidates_recompute__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recorders_api_evaluation_recorders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecorderSummary"][];
                };
            };
        };
    };
    active_peek_api_evaluation_active_peek_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    run_evaluation_api_evaluation_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_api_evaluation_results__recorder_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recorder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_evaluation_compare_get: {
        parameters: {
            query: {
                /** @description recorder_id of baseline (A) */
                a: string;
                /** @description recorder_id of challenger (B) */
                b: string;
                top_k?: number;
                cost_bps?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_peek_api_inference_active_peek_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceJob"] | null;
                };
            };
        };
    };
    inference_status_api_inference_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceStatus"];
                };
            };
        };
    };
    get_job_api_inference_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_api_inference_run_now_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invalidate_api_internal_cache_invalidate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    active_peek_api_analysis_active_peek_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJob"] | null;
                };
            };
        };
    };
    status_api_analysis_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatus"];
                };
            };
        };
    };
    get_job_api_analysis_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_now_api_analysis_run_now_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerResponse"];
                };
            };
        };
    };
    get_for_symbol_api_analysis__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiAnalysis"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    internal_refresh_api_internal_analysis_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerResponse"];
                };
            };
        };
    };
    get_schedule_api_scheduling_retrain_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrainScheduleRead"];
                };
            };
        };
    };
    put_schedule_api_scheduling_retrain_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrainScheduleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrainScheduleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_now_api_scheduling_retrain_run_now_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunNowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrain_job_status_api_scheduling_retrain_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrain_active_peek_api_scheduling_retrain_jobs_active_peek_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    run_training_api_training_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_job_api_training_jobs_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJobStatus"] | null;
                };
            };
        };
    };
    job_status_api_training_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJobStatus"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    training_runs_api_training_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingRunRow"][];
                };
            };
        };
    };
}
